# Generated by Django 2.0.3 on 2018-05-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addsection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addsection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
