# Generated by Django 2.0.3 on 2018-05-07 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addsection', '0002_auto_20180506_1708'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Addsection',
        ),
    ]
