# Generated by Django 2.0.3 on 2018-05-07 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CV',
        ),
    ]
